version: "3"
services:
  mongodb:
    image: mongo
    ports:
    - "27017:27017"
  empleados:
    build: .
    ports:
    - "8081:8081"
    environment:
    - spring.data.mongodb.host=mongodb
    depends_on:
    - mongodb

